name: Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/nowinseoul:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/nowinseoul:latest
            docker stop nowinseoul || true
            docker rm nowinseoul || true
            docker run -d --name nowinseoul --env-file /home/ubuntu/SESAC/nowinseoul/.env \
                -v /run/nowinseoul:/run/nowinseoul \
                -v /home/ubuntu/SESAC/nowinseoul/instance:/app/instance \
                -v /home/ubuntu/SESAC/nowinseoul/static:/app/static \
                ${{ secrets.DOCKER_HUB_USERNAME }}/nowinseoul:latest
            sudo setfacl -R -m u:www-data:rx /home/ubuntu/SESAC/nowinseoul/static
            sudo setfacl -R -m u:www-data:rx /home/ubuntu/SESAC/nowinseoul/${{ secrets.DB_PATH }}
            sudo setfacl -R -d -m u:www-data:rx /home/ubuntu/SESAC/nowinseoul/static
