name: Flask CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/SESAC/nowinseoul
            git fetch origin main
            git reset --hard origin/main
            source /home/ubuntu/SESAC/sesac/bin/activate
            pip install -r requirements.txt
# sudo systemctl restart nowinseoul
# pm2 restart nowinseoul || pm2 start "gunicorn -w 2 --bind 0.0.0.0:8000 app:app" --name nowinseoul
